FROM node:14-alpine

WORKDIR /usr/src/app

COPY *.json .

RUN npm install
RUN npm install apidoc -g

COPY src src
COPY env .

RUN npm run build
RUN apidoc -i src -o dist/docs

EXPOSE 8000

CMD ["npm", "run", "prod"]

