version: '3'

services:
    nginx-rproxy-service:
        image: nginx:1.21-alpine
        container_name: nginx-rproxy-service
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '8080:8080'
        restart: unless-stopped

    doctrinedb-service:
        image: mongo:latest
        container_name: doctrinedb-service
        volumes:
            - ./database/db:/data/db
            - ./database/import:/data/import
        restart: unless-stopped
        depends_on:
          - nginx-rproxy-service


    restapi-v01-service:
        build:
            context: ./../backend
            dockerfile: Dockerfile.RestAPI

        #volumes:
            #- ./backend/logs:/usr/src/app/logs
        #ports:
        #    - 3000:8000
        restart: unless-stopped
        depends_on:
          - doctrinedb-service